# Generated by Django 6.0.5 on 2026-05-24 12:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP_PROCUREMENT', 'SAP Procurement & Fuel'), ('UTILITY_ELECTRICITY', 'Utility Electricity'), ('TRAVEL_CONCUR', 'Corporate Travel (Concur)')], max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.CharField(default='system', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NormalizedEmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', models.CharField(choices=[('SAP_PROCUREMENT', 'SAP Procurement & Fuel'), ('UTILITY_ELECTRICITY', 'Utility Electricity'), ('TRAVEL_CONCUR', 'Corporate Travel (Concur)')], max_length=50)),
                ('scope_category', models.CharField(choices=[('SCOPE_1', 'Scope 1 (Direct)'), ('SCOPE_2', 'Scope 2 (Indirect - Owned)'), ('SCOPE_3', 'Scope 3 (Indirect - Value Chain)')], max_length=20)),
                ('date_start', models.DateField(blank=True, null=True)),
                ('date_end', models.DateField(blank=True, null=True)),
                ('quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=20, null=True)),
                ('normalized_unit', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending Review'), ('APPROVED', 'Approved (Locked)'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('is_edited', models.BooleanField(default=False)),
                ('raw_payload', models.JSONField(help_text='The exact original row or object from the source')),
                ('validation_errors', models.JSONField(blank=True, default=dict, help_text='Any normalization or mapping errors')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('upload', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='ingestion.dataupload')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='ingestion.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('changed_by', models.CharField(max_length=255)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('field_name', models.CharField(max_length=255)),
                ('old_value', models.TextField(blank=True, null=True)),
                ('new_value', models.TextField(blank=True, null=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='ingestion.normalizedemissionrecord')),
            ],
        ),
        migrations.AddField(
            model_name='dataupload',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='ingestion.tenant'),
        ),
    ]
